spring:
 application:
  name: notification-service
 activemq:
  user: admin
  password: admin
  broker-url: tcp://activemq:61616?jms.redeliveryPolicy.maximumRedeliveries=1

server:
 port: 9000

eureka:
 client:
  service-url:
   defaultZone: http://discovery-server:8081/eureka
  register-with-eureka: true
  fetch-registry: true

opentracing: 
 jaeger:
  http-sender:
   url: http://jaeger-allinone:14268/api/traces